services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Infrastructure\Account\Repository\AccountRepository:
        class: App\Infrastructure\Account\Repository\AccountRepository
        factory: ['@doctrine', 'getRepository']
        arguments:
           - App\Domain\Account\Account

    App\Infrastructure\Doctrine\Extension\CurrentAccountExtension:
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 10 }
            - { name: api_platform.doctrine.orm.query_extension.item }
