parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        dql:
            string_functions:
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR: DoctrineExtensions\Query\Mysql\Year
                DAY: DoctrineExtensions\Query\Mysql\Day
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App\Infrastructure\Auth:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infrastructure/Auth'
                prefix: 'App\Infrastructure\Auth'
                alias: Auth
            App\Domain:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain'
                prefix: 'App\Domain'
                alias: App

#            App\Infrastructure\Queue:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Infrastructure/Queue'
#                prefix: 'App\Infrastructure\Queue'
#                alias: Queue
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
