<?php

namespace App\Infrastructure\Subscriber\Repository;

use App\Infrastructure\Doctrine\Repository\DoctrineRepository;

/**
 * RoleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberRepository extends DoctrineRepository
{
}
