monolog:
    handlers:
        main:
            type: rotating_file
            level: info
            max_files: 5
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%-error.log"
            level: error
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
