#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api:
    prefix: /api
    resource: '.'
    type:     'api_platform'

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

logout:
  path: /logout

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

dtc_queue:
    resource: '@DtcQueueBundle/Resources/config/routing.yml'
    prefix:   /admin

jmose_command_scheduler:
    resource: "@JMoseCommandSchedulerBundle/Resources/config/routing.yml"
    prefix:   /admin
