<?php

namespace App\Infrastructure\Project\Repository;

use App\Infrastructure\Doctrine\Repository\DoctrineRepository;

/**
 * TemplateRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends DoctrineRepository
{
}
