<?php

namespace App\Infrastructure\Profile\Repository;

use App\Infrastructure\Doctrine\Repository\DoctrineRepository;

/**
 * ProfileRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends DoctrineRepository
{
}
