<?php

namespace App\Infrastructure\Template\Repository;

use App\Infrastructure\Doctrine\Repository\DoctrineRepository;

/**
 * TemplateRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends DoctrineRepository
{
    /**
     * @param string $name
     *
     * @return mixed
     *
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByNameWithDetails(string $name)
    {
        return $this->createQueryBuilder('t')
            ->where('t.name = :name')
            ->setParameter('name', $name)
            ->join('t.sections', 'ts')
            ->getQuery()
            ->getSingleResult();
    }
}
